/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  prepSidebar: [{type: 'autogenerated', dirName: 'Preparation'}],
  unit1Sidebar: [{type: 'autogenerated', dirName: 'Unit 1'}],
  unit2Sidebar: [{type: 'autogenerated', dirName: 'Unit 2'}],
  unit3Sidebar: [{type: 'autogenerated', dirName: 'Unit 3'}],
  unit4Sidebar: [{type: 'autogenerated', dirName: 'Unit 4'}],
};

module.exports = sidebars;
